<?xml version="1.0" encoding="utf-8"?><Database Name="QLCuaHangBanQA" Class="DBStyleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=XUANDUZ\SQLEXPRESS;Initial Catalog=QLCuaHangBanQA;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLCuaHangBanQAConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.style" Member="styles">
    <Type Name="style">
      <Column Name="ST_id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ST_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ST_slug" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>